export const PCW_ERROR_CODES = {
  CONFIG_INVALID: "PCW_CONFIG_INVALID",
  WORKSTREAM_NOT_FOUND: "PCW_WORKSTREAM_NOT_FOUND",
  CONTEXT_NOT_CONFIGURED: "PCW_CONTEXT_NOT_CONFIGURED",
  PATH_UNSAFE: "PCW_PATH_UNSAFE",
  SOURCE_ERROR: "PCW_SOURCE_ERROR",
  INVENTORY_ERROR: "PCW_INVENTORY_ERROR",
  CONTINUITY_NOT_CONFIGURED: "PCW_CONTINUITY_NOT_CONFIGURED",
  CONTINUITY_INVALID: "PCW_CONTINUITY_INVALID",
  CONTINUITY_STALE: "PCW_CONTINUITY_STALE",
  INTERNAL_ERROR: "PCW_INTERNAL_ERROR"
} as const;

export type PcwErrorCode =
  typeof PCW_ERROR_CODES[keyof typeof PCW_ERROR_CODES];
