#ifndef RuntimeDir
  #error RuntimeDir must identify an explicit prebuilt Standard runtime directory
#endif
#ifndef OutputDir
  #error OutputDir must be explicit
#endif
#ifndef AppVersion
  #error AppVersion must come from Standard runtime metadata
#endif
#ifndef CoreSha256
  #error CoreSha256 must come from Standard runtime metadata
#endif
#ifndef RuntimeSchemaVersion
  #error RuntimeSchemaVersion must come from Standard runtime metadata
#endif
#ifndef InstallerMetadataFile
  #error InstallerMetadataFile must be generated by the installer build helper
#endif

#define AppName "PCW"
#define PrototypeBaseName "PCW-Setup-0.3.0-beta.1-prototype"

[Setup]
AppId={{F464D657-5CE8-4E9B-A51B-AB613862CA18}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher=AI4Context
DefaultDirName={localappdata}\Programs\AI4Context\PCW
DefaultGroupName=AI4Context\PCW
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir={#OutputDir}
OutputBaseFilename={#PrototypeBaseName}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName=PCW {#AppVersion} Standard prototype
LicenseFile={#RuntimeDir}\core\PRIVATE-BETA-TERMS.md
SetupLogging=yes

[Dirs]
Name: "{userprofile}\PCW"; Flags: uninsneveruninstall

[Files]
Source: "{#RuntimeDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#InstallerMetadataFile}"; DestDir: "{app}\metadata"; DestName: "installer.json"; Flags: ignoreversion

[Code]
var
  ContextModePage: TInputOptionWizardPage;
  ContextPage: TInputDirWizardPage;
  ClientPage: TInputOptionWizardPage;
  RegistrationPage: TInputQueryWizardPage;
  ReviewPage: TOutputMsgMemoWizardPage;
  VerificationPage: TOutputMsgMemoWizardPage;
  VerificationSucceeded: Boolean;

function Quote(const Value: String): String;
begin
  Result := Value;
  StringChangeEx(Result, '"', '\"', True);
  Result := '"' + Result + '"';
end;

function StateRoot(): String;
begin
  Result := ExpandConstant('{localappdata}\AI4Context\PCW\state');
end;

function SetupHelperPath(): String;
begin
  Result := ExpandConstant('{app}\core\standard-tools\standard-setup.mjs');
end;

function PortableNodePath(): String;
begin
  Result := ExpandConstant('{app}\runtime\node.exe');
end;

function ResultFilePath(): String;
begin
  Result := ExpandConstant('{tmp}\pcw-standard-setup-result.json');
end;

function RunSetupHelper(const CommandName, ExtraArguments: String; var ResultText: String): Boolean;
var
  ExitCode: Integer;
  Parameters: String;
  ResultPath: String;
begin
  ResultPath := ResultFilePath();
  DeleteFile(ResultPath);
  Parameters := Quote(SetupHelperPath()) + ' ' + CommandName + ' ' + ExtraArguments +
    ' --result-file ' + Quote(ResultPath);
  Result := Exec(PortableNodePath(), Parameters, ExpandConstant('{app}'), SW_HIDE,
    ewWaitUntilTerminated, ExitCode) and (ExitCode = 0);
  if FileExists(ResultPath) then
    LoadStringFromFile(ResultPath, ResultText)
  else
    ResultText := '{"ok":false,"error":{"code":"missing-result","message":"Setup helper returned no result"}}';
  Log('PCW setup helper ' + CommandName + ': ' + ResultText);
end;

function CommonArguments(): String;
begin
  Result := '--runtime-root ' + Quote(ExpandConstant('{app}')) +
    ' --context-root ' + Quote(ContextPage.Values[0]) +
    ' --state-root ' + Quote(StateRoot()) +
    ' --home-directory ' + Quote(ExpandConstant('{userprofile}')) +
    ' --registration-name ' + Quote(RegistrationPage.Values[0]);
end;

procedure InitializeWizard();
begin
  ContextModePage := CreateInputOptionPage(wpSelectDir, 'PCW Context',
    'Create or use a PCW context',
    'Each project has its own context root. One PCW installation can serve multiple context roots.',
    True, True);
  ContextModePage.Add('Create a new empty PCW context');
  ContextModePage.Add('Use an existing PCW context');
  ContextModePage.Values[0] := True;

  ContextPage := CreateInputDirPage(ContextModePage.ID, 'PCW Context location',
    'Choose one PCW context root',
    'For multiple projects, use separate folders such as PCW\Project-A and PCW\Project-B.');
  ContextPage.Add('PCW context root:');
  ContextPage.Values[0] := ExpandConstant('{userprofile}\PCW\My-PCW-Context');

  ClientPage := CreateInputOptionPage(ContextPage.ID, 'Client integration',
    'Choose optional client setup',
    'Cursor can be configured automatically. Codex is guided setup. Claude Desktop is guided and MCP Bundle is planned.',
    False, False);
  ClientPage.Add('Configure Cursor automatically');
  ClientPage.Add('Show Codex guided setup information');
  ClientPage.Add('Show Claude Desktop guided setup information');

  RegistrationPage := CreateInputQueryPage(ClientPage.ID, 'Registration name',
    'Name this PCW context in MCP clients',
    'The bundled setup helper validates this name using the same rules as PCW client integration.');
  RegistrationPage.Add('Registration name:', False);
  RegistrationPage.Values[0] := 'PCW - Existing Context';

  ReviewPage := CreateOutputMsgMemoPage(RegistrationPage.ID, 'Review',
    'Ready to install PCW', 'Review the selected context and client behavior.', '');
  VerificationPage := CreateOutputMsgMemoPage(wpInstalling, 'Verification',
    'PCW verification', 'Runtime, context, integration and Doctor results.', 'Pending');
  VerificationSucceeded := False;
end;

procedure CurPageChanged(CurPageID: Integer);
var
  ClientSummary: String;
  ContextMode: String;
begin
  if CurPageID = ReviewPage.ID then begin
    if ContextModePage.Values[0] then
      ContextMode := 'Create new empty context'
    else
      ContextMode := 'Use existing context';
    ClientSummary := 'No automatic client changes';
    if ClientPage.Values[0] then ClientSummary := 'Cursor: automatic configuration';
    if ClientPage.Values[1] then ClientSummary := ClientSummary + #13#10 + 'Codex: guided setup only';
    if ClientPage.Values[2] then ClientSummary := ClientSummary + #13#10 + 'Claude Desktop: guided setup only';
    ReviewPage.RichEditViewer.Text :=
      'Install location:' + #13#10 + WizardDirValue + #13#10#13#10 +
      'Context mode:' + #13#10 + ContextMode + #13#10#13#10 +
      'Context root:' + #13#10 + ContextPage.Values[0] + #13#10#13#10 +
      'Registration:' + #13#10 + RegistrationPage.Values[0] + #13#10#13#10 +
      ClientSummary + #13#10#13#10 +
      'PCW never deletes the selected context.';
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = ContextPage.ID then begin
    if Trim(ContextPage.Values[0]) = '' then begin
      MsgBox('Choose a PCW context root.', mbError, MB_OK);
      Result := False;
    end
    else if ContextModePage.Values[1] and
      ((not DirExists(ContextPage.Values[0])) or
       (not FileExists(AddBackslash(ContextPage.Values[0]) + 'pcw.yml'))) then begin
      MsgBox('Select an existing PCW context directory containing pcw.yml.',
        mbError, MB_OK);
      Result := False;
    end;
  end;
  if (CurPageID = RegistrationPage.ID) and (Trim(RegistrationPage.Values[0]) = '') then begin
    MsgBox('Enter a registration name. The PCW setup helper performs final validation after runtime installation.', mbError, MB_OK);
    Result := False;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultText: String;
  Summary: String;
  Arguments: String;
begin
  if CurStep <> ssPostInstall then Exit;
  Summary := '';
  Arguments := '--runtime-root ' + Quote(ExpandConstant('{app}')) +
    ' --context-root ' + Quote(ContextPage.Values[0]);
  if ContextModePage.Values[0] then begin
    if not RunSetupHelper('init-context', Arguments, ResultText) then begin
      VerificationPage.RichEditViewer.Text :=
        'The new context could not be initialized safely.' + #13#10 + ResultText;
      Exit;
    end;
    Summary := 'Context: initialized empty (zero workstreams)' + #13#10;
  end;
  if not RunSetupHelper('validate-context', Arguments, ResultText) then begin
    VerificationPage.RichEditViewer.Text := Summary +
      'The selected context is not valid.' + #13#10 + ResultText;
    Exit;
  end;
  Summary := Summary + 'Context: valid' + #13#10;

  if ClientPage.Values[0] then begin
    Arguments := CommonArguments() + ' --client cursor';
    if not RunSetupHelper('plan', Arguments, ResultText) then begin
      VerificationPage.RichEditViewer.Text := Summary + 'Cursor plan failed:' + #13#10 + ResultText;
      Exit;
    end;
    if not RunSetupHelper('apply', Arguments + ' --allow-update', ResultText) then begin
      VerificationPage.RichEditViewer.Text := Summary + 'Cursor integration failed. The runtime remains installed and the context was not changed.' + #13#10 + ResultText;
      Exit;
    end;
    Summary := Summary + 'Cursor: configured and verified' + #13#10;
  end;

  if ClientPage.Values[1] then begin
    Arguments := CommonArguments() + ' --client codex';
    if RunSetupHelper('plan', Arguments, ResultText) then
      Summary := Summary + 'Codex: guided setup generated; no config.toml change' + #13#10;
  end;
  if ClientPage.Values[2] then begin
    Arguments := CommonArguments() + ' --client claude-desktop';
    if RunSetupHelper('plan', Arguments, ResultText) then
      Summary := Summary + 'Claude Desktop: guided setup generated; no JSON change' + #13#10;
  end;

  Arguments := '--runtime-root ' + Quote(ExpandConstant('{app}')) +
    ' --context-root ' + Quote(ContextPage.Values[0]);
  if not RunSetupHelper('doctor', Arguments, ResultText) then begin
    VerificationPage.RichEditViewer.Text := Summary + 'PCW Doctor reported a problem:' + #13#10 + ResultText;
    Exit;
  end;
  VerificationSucceeded := True;
  VerificationPage.RichEditViewer.Text := Summary + 'PCW Doctor: healthy' + #13#10#13#10 +
    'PCW is installed. Restart or reload configured clients before use.';
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultText: String;
  Arguments: String;
begin
  if CurUninstallStep <> usUninstall then Exit;
  if MsgBox('Remove PCW-owned client registrations? Context roots and recovery backups will be preserved.',
    mbConfirmation, MB_YESNO) = IDYES then begin
    Arguments := '--state-root ' + Quote(StateRoot()) + ' --all-owned';
    if not RunSetupHelper('remove', Arguments, ResultText) then
      MsgBox('Some PCW registrations could not be removed safely. They were left unchanged. Details are in the uninstall log.', mbError, MB_OK);
  end;
end;

procedure DeinitializeSetup();
begin
  DeleteFile(ResultFilePath());
end;
